### ISSUE TITLE
std is included even in no_std environments.

### ISSUE THREAD

**Issue by Reisen** [sodiumoxide/sodiumoxide#197]
I am trying to write a piece of code targeting the x86_64 ABI using a custom target, which means there's no `std` available for my build target so I am building with `#[no_std]`. It seems that even with the std flag disabled, the package still tries to pull an `std` package into the build. The following is the build error:

```bash
$ xargo build --release --target=raw
   Compiling pkg-config v0.3.9
   Compiling libc v0.2.36
   Compiling rlibc v1.0.0
   Compiling compiler_builtins v0.1.0 (https://github.com/rust-lang-nursery/compiler-builtins#0ba07e49)
error[E0463]: can't find crate for `std`
  |
  = note: the `raw` target may not be installed

error: aborting due to previous error

```

Note I am not actually doing anything with the package yet, if I remove it from my dependencies the build succeeds and no `std` is ever built.

My environment:

#### Cargo.toml
```toml
# ...
[dependencies.sodiumoxide]                                                                                                                                                                                                                                                    
version = "*"                                                                                                                                                                                                                                                                 
default-features = false     
features=[]
```

#### raw.json
```json
  {                                                                                                                                                                                                                                                                             
    "pre-link-args"                    : ["-m64", "-nostdlib", "-static"],                                                                                                                                                                                                      
    "dynamic-linking"                  : false,                                                                                                                                                                                                                                 
    "relocation-model"                 : "pic",                                                                                                                                                                                                                                 
    "no-compiler-rt"                   : true,                                                                                                                                                                                                                                  
    "no-default-libraries"             : true,                                                                                                                                                                                                                                  
    "position-independent-executables" : false,                                                                                                                                                                                                                                 
    "llvm-target"                      : "x86_64-unknown-none",                                                                                                                                                                                                                 
    "data-layout"                      : "e-m:e-i64:64-f80:128-n8:16:32:64-S128",                                                                                                                                                                                               
    "linker-flavor"                    : "gcc",                                                                                                                                                                                                                                 
    "target-endian"                    : "little",                                                                                                                                                                                                                              
    "target-pointer-width"             : "64",                                                                                                                                                                                                                                  
    "target-c-int-width"               : "32",                                                                                                                                                                                                                                  
    "arch"                             : "x86_64",                                                                                                                                                                                                                              
    "os"                               : "none",                                                                                                                                                                                                                                
    "disable-redzone"                  : true,                                                                                                                                                                                                                                  
    "features"                         : "+avx,+mmx,+sse",                                                                                                                                                                                                                      
    "panic-strategy"                   : "abort"                                                                                                                                                                                                                                
  }
```

**Comment by dnaq** [comment]
Please see #203

**Comment by kinggoesgaming** [comment]
Seemingly we don't have a `#![no_std]` in https://github.com/sodiumoxide/sodiumoxide/blob/master/libsodium-sys/lib.rs

**Comment by nvesely** [comment]
Note: [this](https://github.com/dalek-cryptography/subtle/pull/18/files) looks like a useful pattern.

**Comment by nvesely** [comment]
Okay, so libsodium-sys cannot build without std because bindgen requires std. So hypothetically if libsodium-sys gets built on a system with std and then used on a system without std, then sodiumoxide can be updated and rebuilt without std. And for that matter any project that uses libsodium-sys or sodiumoxide could also rebuild on top of an already-built libsodium-sys without needing std. Not sure how useful this actually would be in any real-world scenarios.

Also, after a little more review it seems pretty clear that the crate currently cannot run with `no_std`. In addition to the implementing the pattern above by including an unconditionally compiled `#![no_std]` at the root, we can also use `xargo` to actually test our build runs in a real std-less environment in Travis. Adding a matrix build something like:

```yml
    - env: TARGET=thumbv7em-none-eabi
      script: 
        - cargo build --no-default-features --target $TARGET
        - xargo test --no-default-features --target $TARGET
      install:
        - cargo install xargo || true
        - rustup target install armv7-unknown-linux-gnueabihf
        - rustup component add rust-src
```

Finally we gotta document it, and just in case it's useful we might provide instructions on how to build for no_std environments and re-compile on top of the existing built code as I explained is hypothetically possible above.
